# Generated by Django 3.0 on 2024-11-24 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branchname', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=50)),
                ('Taluk', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('Taluk', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('adhar', models.CharField(max_length=50)),
                ('pancard', models.CharField(max_length=50)),
                ('fathername', models.CharField(max_length=50)),
                ('mothername', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('occupation', models.CharField(max_length=50)),
                ('previoucompany', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('sallery', models.CharField(max_length=50)),
                ('start_date', models.CharField(max_length=50)),
                ('end_date', models.CharField(max_length=50)),
                ('jrole', models.CharField(max_length=50)),
                ('doj', models.CharField(max_length=50)),
                ('adhar_doc', models.FileField(upload_to='pdfs/')),
                ('pan_doc', models.FileField(upload_to='pdfs/')),
                ('bank_doc', models.FileField(upload_to='pdfs/')),
                ('exp_doc', models.FileField(upload_to='pdfs/')),
                ('tenthpass', models.CharField(max_length=50)),
                ('tenth_percentage', models.CharField(max_length=50)),
                ('twelfth_pass', models.CharField(max_length=50)),
                ('twelfth_percentage', models.CharField(max_length=50)),
                ('degree', models.CharField(max_length=50)),
                ('degreepass', models.CharField(max_length=50)),
                ('degree_percentage', models.CharField(max_length=50)),
                ('pf', models.CharField(max_length=50)),
                ('esic', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('account_holder_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emp_id', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=100)),
                ('branchname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Itemname', models.CharField(max_length=100)),
                ('qty', models.IntegerField()),
                ('price', models.CharField(max_length=100)),
                ('part_no', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('godown', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('utype', models.CharField(max_length=50)),
                ('employee_name', models.CharField(max_length=50)),
                ('branchname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Itemname', models.CharField(max_length=100)),
                ('qty', models.IntegerField()),
                ('price', models.CharField(max_length=100)),
                ('part_no', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('branchname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TransferredItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('source_branch', models.CharField(max_length=255)),
                ('destination_branch', models.CharField(max_length=255)),
                ('transfer_date', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='hp_app.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('source_branch', models.CharField(max_length=255)),
                ('destination_branch', models.CharField(max_length=255)),
                ('transfer_date', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hp_app.Stock')),
            ],
        ),
    ]
