# Generated by Django 3.0 on 2024-11-25 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hp_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='godown',
        ),
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='qty',
        ),
    ]
