# Generated by Django 3.0 on 2024-11-25 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hp_app', '0002_auto_20241125_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='esic',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='fathername',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='mothername',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='previoucompany',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='role',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='sallery',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='start_date',
        ),
    ]
