# Generated by Django 3.0 on 2024-11-25 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp_app', '0003_auto_20241125_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=500, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendorName', models.CharField(max_length=500, null=True)),
                ('companyName', models.CharField(max_length=500, null=True)),
                ('vendorAddress', models.CharField(max_length=500, null=True)),
                ('vendorPhone', models.CharField(max_length=500, null=True)),
                ('companyPhone', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Itemname',
            new_name='spare',
        ),
        migrations.RemoveField(
            model_name='item',
            name='part_no',
        ),
        migrations.AddField(
            model_name='item',
            name='material',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
