# Generated by Django 3.0 on 2024-11-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp_app', '0004_auto_20241125_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
    ]
