# Generated by Django 3.0 on 2024-11-25 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hp_app', '0005_auto_20241125_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='mobile',
        ),
    ]
