# Generated by Django 3.0 on 2024-11-25 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hp_app', '0007_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Role',
            new_name='Jobrole',
        ),
    ]
