# Generated by Django 3.0 on 2024-11-25 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hp_app', '0008_auto_20241125_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobrole',
            old_name='jobrole',
            new_name='jobRole',
        ),
    ]
