# Generated by Django 3.0 on 2024-11-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp_app', '0010_machine_spareparts'),
    ]

    operations = [
        migrations.AddField(
            model_name='spareparts',
            name='spareNo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
