# Generated by Django 3.0 on 2024-11-25 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hp_app', '0011_spareparts_spareno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spareparts',
            old_name='spareNo',
            new_name='sparepartNo',
        ),
    ]
