# Generated by Django 3.0 on 2024-11-25 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hp_app', '0012_auto_20241125_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spareparts',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='spareparts',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hp_app.Machine'),
        ),
        migrations.AlterField(
            model_name='spareparts',
            name='sparepart',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='spareparts',
            name='sparepartNo',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
