# Generated by Django 3.0 on 2024-11-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp_app', '0013_auto_20241125_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spareparts',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='spareparts',
            name='machine',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='spareparts',
            name='sparepart',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='spareparts',
            name='sparepartNo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
