# Generated by Django 3.0 on 2024-11-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp_app', '0015_auto_20241126_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='machinephoto',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='spareparts',
            name='sparephoto',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
