# Generated by Django 3.0 on 2024-11-26 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hp_app', '0016_auto_20241126_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='photo',
        ),
    ]
