# Generated by Django 3.0 on 2024-11-26 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hp_app', '0017_remove_employee_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='photo',
        ),
    ]
