# Generated by Django 3.0 on 2024-11-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp_app', '0020_employee_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spareparts',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='spareparts',
            name='machine',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='spareparts',
            name='sparepart',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='spareparts',
            name='sparepartNo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='spareparts',
            name='sparephoto',
            field=models.ImageField(blank=True, null=True, upload_to='spareparts/'),
        ),
    ]
