# Generated by Django 3.0 on 2024-11-26 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp_app', '0022_auto_20241126_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='StocktoDept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machineName', models.CharField(max_length=500, null=True)),
                ('sparePart', models.CharField(max_length=500, null=True)),
                ('sparePartNo', models.CharField(max_length=500, null=True)),
                ('qty', models.IntegerField(max_length=500, null=True)),
            ],
        ),
    ]
