# Generated by Django 3.0 on 2024-11-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp_app', '0023_stocktodept'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktodept',
            name='department',
            field=models.IntegerField(max_length=500, null=True),
        ),
    ]
