# Generated by Django 3.0 on 2024-11-26 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp_app', '0024_stocktodept_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktodept',
            name='department',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
